// <auto-generated />
namespace TrashCollector_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CusomAdress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CusomAdress));
        
        string IMigrationMetadata.Id
        {
            get { return "201808311742319_CusomAdress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
